#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "boringproxy"
name = "Boring Proxy Server"
description.en = "boringproxy is a combination of a reverse proxy and a tunnel manager."
description.fr = "ennuyeuxproxy est une combinaison d'un proxy inverse et d'un gestionnaire de tunnel."

version = "0.10.0~ynh1"

maintainers = ["God"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "MIT"
website = "https://boringproxy.io/"
admindoc = "https://boringproxy.io/usage/"
code = "https://github.com/boringproxy/boringproxy/"

[integration]
yunohost = ">= 11.2"
# FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    
[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/boringproxy/boringproxy/releases/download/v0.10.0/boringproxy-linux-x86_64"
        amd64.sha256 = "unknown"
        arm64.url = "https://github.com/boringproxy/boringproxy/releases/download/v0.10.0/boringproxy-linux-arm64"
        arm64.sha256 = "7a778797dd640eb51defe912e8b6872df92241927193106590a2ccb92a5dc926"
        armhf.url = "https://github.com/boringproxy/boringproxy/releases/download/v0.10.0/boringproxy-linux-arm"
        armhf.sha256 = "unknown"
        i386.url = "https://github.com/boringproxy/boringproxy/releases/download/v0.10.0/boringproxy-linux-386"
        i386.sha256 = "unknown"
        rename = "boringproxy"

        # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "boringproxy-linux-x86_64"
        autoupdate.asset.arm64 = "boringproxy-linux-arm64"
        autoupdate.asset.armhf = "boringproxy-linux-arm"
        autoupdate.asset.i386 = "boringproxy-linux-386"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    tunnels.url = "/tunnels"
    tunnels.show_tile = false
    tunnels.protected= true
    tunnels.auth_header = false
    tunnels.allowed = ["visitors", "all_users"]

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    Main.default = 443
    main.exposed = "TCP"
    http.default = 80
    http.exposed = "TCP"

